import type { StateCreator } from 'zustand'
import type { StoreState, HandlersSlice } from '../types'

export const createHandlersSlice: StateCreator<StoreState, [], [], HandlersSlice> = (set) => ({
  onOpen: () => {},
  setOpenHandler: (handler) => set({ onOpen: handler }),
  onDownload: () => {},
  setDownloadHandler: (handler) => set({ onDownload: handler }),
  onBatchDownload: () => {},
  setBatchDownloadHandler: (handler) => set({ onBatchDownload: handler }),
  onUpload: () => {},
  setUploadHandler: (handler) => set({ onUpload: handler }),
  onRefresh: () => {},
  setRefreshHandler: (handler) => set({ onRefresh: handler }),
  onSavePreview: async () => {},
  setSavePreviewHandler: (handler) => set({ onSavePreview: handler }),
  onNavigateToPath: () => {},
  setNavigateToPathHandler: (handler) => set({ onNavigateToPath: handler }),
  onDropFiles: () => {},
  setDropFilesHandler: (handler) => set({ onDropFiles: handler }),
  onRename: async () => {},
  setRenameHandler: (handler) => set({ onRename: handler }),
  onDelete: async () => {},
  setDeleteHandler: (handler) => set({ onDelete: handler }),
  onCreateFolder: async () => {},
  setCreateFolderHandler: (handler) => set({ onCreateFolder: handler }),
  hasRename: false,
  setHasRename: (has) => set({ hasRename: has }),
  hasDelete: false,
  setHasDelete: (has) => set({ hasDelete: has }),
  hasCreateFolder: false,
  setHasCreateFolder: (has) => set({ hasCreateFolder: has }),
  hasUpload: false,
  setHasUpload: (has) => set({ hasUpload: has }),
  hasDownload: false,
  setHasDownload: (has) => set({ hasDownload: has }),
  hasBatchDownload: false,
  setHasBatchDownload: (has) => set({ hasBatchDownload: has }),
})
